
on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev
        docker build -t europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/images/data-ingestion:latest .
        docker push europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/images/data-ingestion:latest

    - name: Deploy to Cloud Run
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud run deploy data-ingestion --image \
        europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/images/data-ingestion:latest \
        --platform managed --region europe-west1 --allow-unauthenticated 
        
